# Generated by Django 4.0.3 on 2025-12-21 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myusers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=10)),
                ('course_name', models.CharField(max_length=50)),
                ('offered_year', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='user_in_course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('P', 'Professor'), ('S', 'Student')], max_length=1)),
                ('request_accepted', models.BooleanField(default=False)),
                ('verification_code', models.CharField(blank=True, max_length=66, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycourses.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myusers.myuser')),
            ],
        ),
    ]
