# Generated by Django 4.0.3 on 2025-12-21 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('department', models.CharField(choices=[('CSE', 'Computer Science and Engineering'), ('MSE', 'Material Science and Engineering'), ('AE', 'Aerospace Engineering'), ('ME', 'Mechanical Engineering'), ('EE', 'Electrical Engineering'), ('MTH', 'Mathematics and Computing'), ('BSBE', 'Biological Science and BioEngineering'), ('CHE', 'Chemical Engineering'), ('CE', 'Civil Engineering')], max_length=4)),
                ('password', models.CharField(max_length=70)),
                ('verified', models.BooleanField(default=False)),
                ('verification_code', models.CharField(blank=True, max_length=66, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=66, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myusers.myuser')),
            ],
        ),
    ]
