# Generated by Django 4.0.3 on 2025-12-21 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mycourses', '0001_initial'),
        ('myusers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_value', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
                ('answer', models.CharField(blank=True, max_length=100)),
                ('question_type', models.CharField(choices=[('S', 'MCQ Single Correct'), ('M', 'MCQ Multi Correct'), ('F', 'Fill in the blank')], max_length=1)),
                ('positive_marks', models.FloatField()),
                ('negative_marks', models.FloatField()),
                ('partial_allowed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.CharField(max_length=1000)),
                ('deadline', models.DateTimeField()),
                ('start_at', models.DateTimeField()),
                ('checked', models.BooleanField(default=False)),
                ('answer_key_visible', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted', models.BooleanField(default=False)),
                ('submission_time', models.DateTimeField(auto_now=True)),
                ('total_marks', models.CharField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='user_quizattempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myquiz.quizattempt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myusers.myuser')),
            ],
        ),
        migrations.CreateModel(
            name='quiz_quizattempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myquiz.quiz')),
                ('quiz_attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myquiz.quizattempt')),
            ],
        ),
        migrations.CreateModel(
            name='quiz_in_course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycourses.course')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myquiz.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='question_in_quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myquiz.question')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myquiz.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='question_attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_answer', models.CharField(blank=True, max_length=100)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myquiz.question')),
                ('quiz_attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myquiz.quizattempt')),
            ],
        ),
        migrations.CreateModel(
            name='Option_in_question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myquiz.option')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myquiz.question')),
            ],
        ),
    ]
